# Generated by Django 4.0.3 on 2022-03-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('chances', models.CharField(choices=[('NETWORK', 'Network'), ('EAT', 'Eat'), ('SWIM', 'Swim'), ('FITNESS', 'Fitness')], max_length=50)),
                ('photo1', models.ImageField(upload_to='hotel_photos/')),
                ('photo2', models.ImageField(upload_to='re_photos/')),
                ('photo3', models.ImageField(upload_to='cafe_photos/')),
                ('cost', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activ'), ('NOT_ACTIVE', 'Not_Active')], max_length=50)),
            ],
        ),
    ]
