# Generated by Django 4.0.3 on 2022-03-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_hotel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
