# Generated by Django 4.0.3 on 2022-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hotel_ig_hotel_phone_num_hotel_tg_restourant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restourant',
            name='ig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restourant',
            name='tg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
