# Generated by Django 4.0.3 on 2022-03-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_restourant_ig_restourant_tg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restourant',
            name='dostavka',
        ),
    ]
