# Generated by Django 4.0.3 on 2022-03-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_restourant_dostavka'),
    ]

    operations = [
        migrations.AddField(
            model_name='restourant',
            name='dostavka',
            field=models.CharField(choices=[('BOR', 'Bor'), ("YO'Q", "Yo'q")], max_length=50, null=True),
        ),
    ]
