# Generated by Django 4.0.3 on 2022-03-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_restourant_dostavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restourant',
            name='dostavka',
            field=models.CharField(choices=[('BOR', 'Bor'), ("YO'Q", "Yo'q")], default='Bor', max_length=50),
        ),
    ]
