# Generated by Django 4.0.3 on 2022-03-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_cafe_chances_remove_hotel_chances_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='t',
            new_name='type',
        ),
    ]
