# Generated by Django 4.0.3 on 2022-03-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_t_cafe_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='t',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='restourant',
            old_name='t',
            new_name='type',
        ),
    ]
