# Generated by Django 4.0.3 on 2022-03-13 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_t_hotel_type_rename_t_restourant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('YEVROPACHA', 'Yevropacha'), ('OSIYOCHA', 'Osiyocha')], max_length=50)),
                ('price', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel')),
            ],
        ),
    ]
