# Generated by Django 4.0.3 on 2022-03-13 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_hotelmenus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestourantMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('YEVROPACHA', 'Yevropacha'), ('OSIYOCHA', 'Osiyocha')], max_length=50)),
                ('price', models.IntegerField()),
                ('restourant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restourant')),
            ],
        ),
        migrations.CreateModel(
            name='CafeMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('YEVROPACHA', 'Yevropacha'), ('OSIYOCHA', 'Osiyocha')], max_length=50)),
                ('price', models.IntegerField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cafe')),
            ],
        ),
    ]
