# Generated by Django 4.0.3 on 2022-03-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_restourantmenus_cafemenus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CafeMenus',
            new_name='CafeMenu',
        ),
        migrations.RenameModel(
            old_name='HotelMenus',
            new_name='HotelMenu',
        ),
        migrations.RenameModel(
            old_name='RestourantMenus',
            new_name='RestourantMenu',
        ),
    ]
